stages:
- test
- integration tests
- package debug

android-env: &android-env
  os: linux
  language: android
  licenses:
  - 'android-sdk-license-.+'
  android:
    components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - sys-img-x86-android-28
  jdk: oraclejdk8
  sudo: false
  addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - libstdc++6
      - fonts-droid
  before_script:
  - ./ci/setupFlutter.sh
  - git clone --depth 1 https://github.com/fsaintjacques/semver-tool /tmp/semver &> /dev/null
  - LAST_VERSION=$(git show version:latest.txt)
  - VERSION=$(/tmp/semver/src/semver bump build $TRAVIS_BUILD_NUMBER $LAST_VERSION)

ios-env: &ios-env
  os: osx
  language: generic
  osx_image: xcode10.1
  before_script:
  - ./ci/ios/setupEnvironment.sh
  - ./ci/setupFlutter.sh
  - git clone --depth 1 https://github.com/fsaintjacques/semver-tool /tmp/semver &> /dev/null
  - LAST_VERSION=$(git show version:latest.txt)
  - VERSION=$(/tmp/semver/src/semver bump build $TRAVIS_BUILD_NUMBER $LAST_VERSION)

matrix:
  fast_finish: true

  allow_failures:
  - stage: package
  - stage: integration tests

  include:
  - stage: test
    os: linux
    language: generic
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - ./ci/setupFlutter.sh
    - ls -la ~
    script:
    - ./flutter/bin/flutter test ./test
    - ls -la ~

  - stage: integration tests
    <<: *android-env
    before_script:
    - ./ci/android/startEmulator.sh
    - ./ci/setupFlutter.sh
    script: ./flutter/bin/flutter drive --target=test_driver/app.dart --debug
  - stage: package debug
    <<: *android-env
    script: ./flutter/bin/flutter build apk --debug --build-name=$VERSION

  - stage: integration tests
    <<: *ios-env
    script: ./flutter/bin/flutter drive --target=test_driver/app.dart --debug
  - stage: package debug
    <<: *ios-env
    script: ./flutter/bin/flutter build ios --no-codesign --debug --build-name=$VERSION

cache:
  directories:
  - $HOME/.pub-cache
#- build/app/outputs/apk/debug/app-debug.apk
#- build/ios/iphoneos/Runner.app
