stages:
- test
- integration tests
- package debug

android-env: &android-env
  os: linux
  language: android
  licenses:
  - android-sdk-license-.+
  android:
    components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - sys-img-armeabi-v7a-android-28
  jdk: oraclejdk8
  sudo: false
  addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - libstdc++6
      - fonts-droid
  before_script:
  - "./ci/setupFlutter.sh"
  - git clone --depth 1 https://github.com/fsaintjacques/semver-tool /tmp/semver &> /dev/null
  - LAST_VERSION=$(git show version:latest.txt)
  - VERSION=$(/tmp/semver/src/semver bump build $TRAVIS_BUILD_NUMBER $LAST_VERSION)
  - ls -la /usr/local/android-sdk/
  - ls -la /usr/local/android-sdk/emulator
  - ls -la /usr/local/android-sdk/platform-tools
  - ls -la /usr/local/android-sdk/tools
  - ls -la /usr/local/android-sdk/tools/bin
  - env

ios-env: &ios-env
  os: osx
  language: generic
  osx_image: xcode10.1
  before_script:
  - "./ci/ios/setupEnvironment.sh"
  - "./ci/setupFlutter.sh"
  - git clone --depth 1 https://github.com/fsaintjacques/semver-tool /tmp/semver &> /dev/null
  - LAST_VERSION=$(git show version:latest.txt)
  - VERSION=$(/tmp/semver/src/semver bump build $TRAVIS_BUILD_NUMBER $LAST_VERSION)

matrix:
  fast_finish: true

  allow_failures:
  - stage: integration tests
  - stage: package debug

  include:
  - stage: test
    os: linux
    language: generic
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - "./ci/setupFlutter.sh"
    - ls -la $HOME/.pub-cache
    script:
    - "./flutter/bin/flutter test ./test"
    - ls -la $HOME/.pub-cache

  - stage: integration tests
    <<: *android-env
    before_script:
    - "./ci/android/startEmulator.sh"
    - "./ci/setupFlutter.sh"
    script: "./flutter/bin/flutter drive --target=test_driver/app.dart --debug"
  - stage: package debug
    <<: *android-env
    script: ./flutter/bin/flutter build apk --debug --build-name=$VERSION
    deploy:
      provider: releases
      api_key:
        secure: mf+M+I+tS+s0RCmeqIsW67Y125hLBtIOhoTqp5ydG9fC6fdGvkHam9q63kpLL47GDHR+HEHJQiEvn3y7p3cwI/0SW1+F3/2+awuHFcTuMgpsdPFcvfdPONiAb4BRLuiS7tUbY/f1fLQK7eNNApZ5vatE/QbIjkWAGh1qxHqq6jXL0j+unIIZhNXFy4cJOkR6lUVGMmoyJz0l5Ow05qADS08uOEqCM2YG5mlKYUc+Nw5ddrs0vVV0SVUxxDGikkMjhWpcLhruDKVeRm2z+dDCntZZ18js2wq4WdlebvqhOL55QkQsVaRYR9YNLEqbfaDFoGAUMJtCExPecf2iGV2PrzK0cty32MnhwE69kiyKZ06GZ/5IYkRXX3oFW1PhjDITLEAGktZSyAfRJY8eYtuAyMeALlFv/AnkGwCraA6fx3xnqgy3FGhyDmkOVKAh2DBiDanE3zJkwdbiDi5czUqKggcsXG8/kid7/6ILD8ucMjOb8lW0O3DjUTUVCuDSiFV5DMLirFmEA81t1oJS/m4htmOeV4o5k2dj5PHsW/v1iZBPjCDtvD7gjr6XRhLzh2wtavxkEw1KFtFvzvrHziYSRzXpJhsgh1toHs6r7VGHQdvOQCL7VIcU6qsvMBYloYlkHPWlP7XBiB8obe+wCkm0rdIV0d71KqVUIfMKKlWE3ag=
      file: build/app/outputs/apk/debug/app-debug.apk
      draft: true
      on.repo: tarbadev/carambar

  - stage: integration tests
    <<: *ios-env
    script: ./flutter/bin/flutter drive --target=test_driver/app.dart --debug
  - stage: package debug
    <<: *ios-env
    script: ./flutter/bin/flutter build ios --no-codesign --debug --build-name=$VERSION
    deploy:
      provider: releases
      api_key:
        secure: mf+M+I+tS+s0RCmeqIsW67Y125hLBtIOhoTqp5ydG9fC6fdGvkHam9q63kpLL47GDHR+HEHJQiEvn3y7p3cwI/0SW1+F3/2+awuHFcTuMgpsdPFcvfdPONiAb4BRLuiS7tUbY/f1fLQK7eNNApZ5vatE/QbIjkWAGh1qxHqq6jXL0j+unIIZhNXFy4cJOkR6lUVGMmoyJz0l5Ow05qADS08uOEqCM2YG5mlKYUc+Nw5ddrs0vVV0SVUxxDGikkMjhWpcLhruDKVeRm2z+dDCntZZ18js2wq4WdlebvqhOL55QkQsVaRYR9YNLEqbfaDFoGAUMJtCExPecf2iGV2PrzK0cty32MnhwE69kiyKZ06GZ/5IYkRXX3oFW1PhjDITLEAGktZSyAfRJY8eYtuAyMeALlFv/AnkGwCraA6fx3xnqgy3FGhyDmkOVKAh2DBiDanE3zJkwdbiDi5czUqKggcsXG8/kid7/6ILD8ucMjOb8lW0O3DjUTUVCuDSiFV5DMLirFmEA81t1oJS/m4htmOeV4o5k2dj5PHsW/v1iZBPjCDtvD7gjr6XRhLzh2wtavxkEw1KFtFvzvrHziYSRzXpJhsgh1toHs6r7VGHQdvOQCL7VIcU6qsvMBYloYlkHPWlP7XBiB8obe+wCkm0rdIV0d71KqVUIfMKKlWE3ag=
      file: build/ios/iphoneos/Runner.app
      draft: true
      on.repo: tarbadev/carambar

cache:
  directories:
  - "$HOME/.pub-cache"
