stages:
- test
- package

matrix:
  include:
  - stage: test
    os: linux
    language: generic
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone --branch v1.2.1 https://github.com/flutter/flutter.git
    - ./flutter/bin/flutter doctor
    script:
    - ./flutter/bin/flutter test ./test

  - stage: package
    os: linux
    language: android
    licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - sys-img-armeabi-v7a-google_apis-28
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
#    - wget http://services.gradle.org/distributions/gradle-4.10.2-bin.zip
#    - unzip -qq gradle-4.10.2-bin.zip
#    - export GRADLE_HOME=$PWD/gradle-4.10.2
#    - export PATH=$GRADLE_HOME/bin:$PATH
    - git clone --branch v1.2.1 --depth 1 https://github.com/flutter/flutter.git
    - ./flutter/bin/flutter doctor
    script:
    - ./flutter/bin/flutter -v build apk

  - stage: package
    os: osx
    language: generic
    osx_image: xcode10.1
    before_script:
    - pip install six
    - brew update
    - brew install --HEAD usbmuxd
    - brew unlink usbmuxd
    - brew link usbmuxd
    - brew install --HEAD libimobiledevice
    - brew install ideviceinstaller ios-deploy
    - git clone --branch v1.2.1 --depth 1 https://github.com/flutter/flutter.git
    - ./flutter/bin/flutter doctor
    script:
    - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
  - $HOME/.pub-cache